[package]
name = "smaller_numbers_than_current_1365"
version = "0.1.0"
authors = ["Matt Jecha <dev@admin01.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
